# This Dockerfile builds the image used during the boost_1_72 build job on
# GitLab.
FROM alpine:3.12
LABEL maintainer="Dirk Stolle <striezel-dev@web.de>"
# Always update any existing packages first.
RUN apk update
# Install build toolchain and dependencies.
RUN apk add boost-dev catch2 cmake g++ jpeg-dev libpng-dev make pkgconf
# Adjust environment variables for preferred compilers.
ENV CXX=g++
ENV CC=gcc
RUN export CXX=g++
RUN export CC=gcc
