name: Alpine

on: push

jobs:
  alpine:
    runs-on: ubuntu-22.04
    container: alpine:latest
    steps:
      # Checks-out the repository under $GITHUB_WORKSPACE.
      - uses: actions/checkout@v4
      - name: Install packages
        run: |
          apk update
          apk add boost-dev catch2 cmake g++ git make jpeg-dev libpng-dev pkgconf
          apk add libjpeg-turbo-static libpng-static zlib-static
      - name: Build statically linked binaries
        run: |
          cd "$GITHUB_WORKSPACE"
          mkdir build-static
          cd build-static
          export GIT_DISCOVERY_ACROSS_FILESYSTEM=1
          cmake ../ -DENABLE_LTO=ON -DENABLE_STATIC_LINKING=ON
          cmake --build . -j2
      - name: Run tests
        run: |
          cd "$GITHUB_WORKSPACE/build-static"
          ctest -V
      - name: Collect statically linked artifacts
        run: |
          cd "$GITHUB_WORKSPACE"
          # gandalf_the_grey
          mkdir -p "$GITHUB_WORKSPACE"/artifacts/gandalf_the_grey
          cp build-static/apps/gandalf_the_grey/gandalf-the-grey artifacts/gandalf_the_grey
          cp apps/gandalf_the_grey/*.md artifacts/gandalf_the_grey
          # gandalf_the_white
          mkdir -p "$GITHUB_WORKSPACE"/artifacts/gandalf_the_white
          cp build-static/apps/gandalf_the_white/gandalf-the-white artifacts/gandalf_the_white
          cp apps/gandalf_the_white/*.md artifacts/gandalf_the_white
          # gimli
          mkdir -p "$GITHUB_WORKSPACE"/artifacts/gimli
          cp build-static/apps/gimli/gimli artifacts/gimli
          cp apps/gimli/*.md artifacts/gimli
          # hobbit
          mkdir -p "$GITHUB_WORKSPACE"/artifacts/hobbit
          cp build-static/apps/hobbit/hobbit artifacts/hobbit
          cp apps/hobbit/*.md artifacts/hobbit
          # LICENSE + readme
          cp LICENSE artifacts/
          cp apps/readme.md artifacts/
      - name: Archive build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: gimli_vX.Y.Z_linux-amd64-generic
          path: |
            artifacts/*
