name: Clang

on: push

jobs:
  ubuntu_20_04_clang:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        version: [8, 9, 10, 11]
    steps:
      # Checks-out the repository under $GITHUB_WORKSPACE.
      - uses: actions/checkout@v2
      - name: Install Debian packages
        run: |
          sudo apt-get update
          sudo apt-get install -y catch cmake clang-${{ matrix.version }} libjpeg-dev libpng-dev pkg-config
          sudo apt-get install -y --no-install-recommends --no-install-suggests libboost-dev
      - name: Build with Clang ${{ matrix.version }}
        run: |
          export CXX=clang++-${{ matrix.version }}
          export CC=clang-${{ matrix.version }}
          cd $GITHUB_WORKSPACE
          mkdir build
          cd build
          cmake ../
          make -j4
      - name: Tests
        run: |
          cd "$GITHUB_WORKSPACE"/build
          ctest -V
