name: GCC

on: push

jobs:
  ubuntu_gcc:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        version: [9, 10, 11, 12]
    steps:
      # Checks-out the repository under $GITHUB_WORKSPACE.
      - uses: actions/checkout@v3
      - name: Install Debian packages
        run: |
          sudo apt-get update
          sudo apt-get install -y catch2 cmake g++-${{ matrix.version }} libjpeg-dev libpng-dev pkg-config
          sudo apt-get install -y --no-install-recommends --no-install-suggests libboost-dev
      - name: Build with GNU GCC ${{ matrix.version }}
        run: |
          export CXX=g++-${{ matrix.version }}
          export CC=gcc-${{ matrix.version }}
          cd $GITHUB_WORKSPACE
          mkdir build
          cd build
          cmake ../
          cmake --build . -j2
      - name: Tests
        run: |
          cd "$GITHUB_WORKSPACE"/build
          ctest -V
      - name: Build statically linked with GNU GCC ${{ matrix.version }}
        run: |
          export CXX=g++-${{ matrix.version }}
          export CC=gcc-${{ matrix.version }}
          cd $GITHUB_WORKSPACE
          mkdir build-static
          cd build-static
          cmake -DENABLE_LTO=ON -DENABLE_STATIC_LINKING=ON ../
          cmake --build . -j2
        # Only run static build on latest version in the matrix.
        if: matrix.version == 12
      - name: Collect build artifacts and documentation
        run: |
          cd "$GITHUB_WORKSPACE"
          mkdir -p "$GITHUB_WORKSPACE"/artifacts/gandalf_the_grey
          cp build-static/apps/gandalf_the_grey/gandalf-the-grey artifacts/gandalf_the_grey/
          cp apps/gandalf_the_grey/*.md artifacts/gandalf_the_grey/
          mkdir -p "$GITHUB_WORKSPACE"/artifacts/gandalf_the_white
          cp build-static/apps/gandalf_the_white/gandalf-the-white artifacts/gandalf_the_white/
          cp apps/gandalf_the_white/*.md artifacts/gandalf_the_white/
          mkdir -p "$GITHUB_WORKSPACE"/artifacts/gimli
          cp build-static/apps/gimli/gimli artifacts/gimli/
          cp apps/gimli/*.md artifacts/gimli/
          mkdir -p "$GITHUB_WORKSPACE"/artifacts/hobbit
          cp build-static/apps/hobbit/hobbit artifacts/hobbit/
          cp apps/hobbit/*.md artifacts/hobbit/
        # Only run static build on latest version in the matrix.
        if: matrix.version == 12
      - name: Archive build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build-gcc-static-linking
          path: |
            artifacts/*
        # Only run static build on latest version in the matrix.
        if: matrix.version == 12
