name: GCC

on: push

jobs:
  gcc:
    strategy:
      fail-fast: false
      matrix:
        include:
          - version: 9
            os: ubuntu-22.04
          - version: 10
            os: ubuntu-24.04
          - version: 12
            os: ubuntu-24.04
          - version: 14
            os: ubuntu-24.04
    runs-on: ${{ matrix.os }}
    steps:
      # Checks-out the repository under $GITHUB_WORKSPACE.
      - uses: actions/checkout@v4
      - name: Install Debian packages
        run: |
          sudo apt-get update
          sudo apt-get install -y catch2 cmake g++-${{ matrix.version }} libjpeg-dev libpng-dev pkg-config
          sudo apt-get install -y --no-install-recommends --no-install-suggests libboost-dev
      - name: Build with GNU GCC ${{ matrix.version }}
        run: |
          export CXX=g++-${{ matrix.version }}
          export CC=gcc-${{ matrix.version }}
          cd $GITHUB_WORKSPACE
          mkdir build
          cd build
          cmake ../
          cmake --build . -j2
      - name: Tests
        run: |
          cd "$GITHUB_WORKSPACE"/build
          ctest -V
      - name: Build statically linked with GNU GCC ${{ matrix.version }}
        run: |
          export CXX=g++-${{ matrix.version }}
          export CC=gcc-${{ matrix.version }}
          cd $GITHUB_WORKSPACE
          mkdir build-static
          cd build-static
          cmake -DENABLE_LTO=ON -DENABLE_STATIC_LINKING=ON ../
          cmake --build . -j2
        # Only run static build on latest version in the matrix.
        if: matrix.version == 14
      - name: Collect build artifacts and documentation
        run: |
          cd "$GITHUB_WORKSPACE"
          # gandalf_the_grey
          mkdir -p "$GITHUB_WORKSPACE"/artifacts/gandalf_the_grey
          cp build-static/apps/gandalf_the_grey/gandalf-the-grey artifacts/gandalf_the_grey/
          cp apps/gandalf_the_grey/*.md artifacts/gandalf_the_grey/
          # gandalf_the_white
          mkdir -p "$GITHUB_WORKSPACE"/artifacts/gandalf_the_white
          cp build-static/apps/gandalf_the_white/gandalf-the-white artifacts/gandalf_the_white/
          cp apps/gandalf_the_white/*.md artifacts/gandalf_the_white/
          # gimli
          mkdir -p "$GITHUB_WORKSPACE"/artifacts/gimli
          cp build-static/apps/gimli/gimli artifacts/gimli/
          cp apps/gimli/*.md artifacts/gimli/
          # hobbit
          mkdir -p "$GITHUB_WORKSPACE"/artifacts/hobbit
          cp build-static/apps/hobbit/hobbit artifacts/hobbit/
          cp apps/hobbit/*.md artifacts/hobbit/
          # license and readme and third-party notices
          cp LICENSE artifacts/
          cp apps/readme.md artifacts/
          cp apps/third-party.md artifacts/
        # Only run static build on latest version in the matrix.
        if: matrix.version == 14
      - name: Archive build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: gimli_vX.Y.Z_linux-amd64-gcc
          path: |
            artifacts/*
        # Only run static build on latest version in the matrix.
        if: matrix.version == 14
