name: MSYS2

on: push

jobs:
  msys2_mingw64:
    runs-on: windows-2022
    defaults:
      run:
        shell: msys2 {0}
    steps:
      # Checks-out the repository under $GITHUB_WORKSPACE.
      - uses: actions/checkout@v4
      - uses: msys2/setup-msys2@v2
        with:
          msystem: mingw64
          update: true
          install: >-
            git
            mingw-w64-x86_64-boost
            mingw-w64-x86_64-catch
            mingw-w64-x86_64-cmake
            mingw-w64-x86_64-gcc
            mingw-w64-x86_64-libjpeg-turbo
            mingw-w64-x86_64-libpng
            mingw-w64-x86_64-ninja
            mingw-w64-x86_64-pkg-config
      - name: Build
        run: |
          export MSYSTEM=MINGW64
          export CXX=g++
          export CC=gcc
          cd "$GITHUB_WORKSPACE"
          mkdir build
          cd build
          cmake ../
          cmake --build . -j2
      - name: Tests
        run: |
          export MSYSTEM=MINGW64
          cd "$GITHUB_WORKSPACE"/build
          ctest -V
      - name: Build statically linked
        run: |
          export MSYSTEM=MINGW64
          export CXX=g++
          export CC=gcc
          cd "$GITHUB_WORKSPACE"
          mkdir build-static
          cd build-static
          cmake -DENABLE_LTO=ON -DENABLE_STATIC_LINKING=ON ../
          cmake --build . -j2
      - name: Collect build artifacts in one place
        run: |
          export MSYSTEM=MINGW64
          cd "$GITHUB_WORKSPACE"
          # gandalf_the_grey
          mkdir -p "$GITHUB_WORKSPACE"/artifacts/gandalf_the_grey
          cp build-static/apps/gandalf_the_grey/gandalf-the-grey.exe artifacts/gandalf_the_grey/
          cp apps/gandalf_the_grey/*.md artifacts/gandalf_the_grey/
          # gandalf_the_white
          mkdir -p "$GITHUB_WORKSPACE"/artifacts/gandalf_the_white
          cp build-static/apps/gandalf_the_white/gandalf-the-white.exe artifacts/gandalf_the_white/
          cp apps/gandalf_the_white/*.md artifacts/gandalf_the_white/
          # gimli
          mkdir -p "$GITHUB_WORKSPACE"/artifacts/gimli
          cp build-static/apps/gimli/gimli.exe artifacts/gimli/
          cp apps/gimli/*.md artifacts/gimli/
          # hobbit
          mkdir -p "$GITHUB_WORKSPACE"/artifacts/hobbit
          cp build-static/apps/hobbit/hobbit.exe artifacts/hobbit/
          cp apps/hobbit/*.md artifacts/hobbit/
          # license + readme
          cp LICENSE artifacts/
          cp apps/readme.md artifacts/
      - name: Archive build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: gimli_vX.Y.Z_win64
          path: |
            artifacts/*
